[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"
primaryColor="#1d1d1d"
backgroundColor="#1d1d1d"
secondaryBackgroundColor="#323232"
textColor="#B9B9B9"
